#!/bin/bash

# Nginx proxy first run setup -----

if [ $( docker network ls --format="{{.Name}}" | grep -E "^proxy$" ) ]; then
  echo "Proxy network already setup, skipping..."
else
  echo "Setting up proxy network..."
  docker network create proxy
fi
