# ===== Docker / Container Management =====
#
# Portainer (arm tag)
#
# ----- Notes -----
#
# Portainer:
#  - https://hub.docker.com/r/portainer/portainer 
#  - https://github.com/portainer/portainer

version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer:arm
    networks:
      - default
    ports:
     - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/data:/data
    restart: unless-stopped
