# ===== Docker / Container Management =====
#
# Portainer (arm tag)
#
# ----- Notes -----
#
# Links:
#  - https://portainer.io/install.html
#
# Repos:
#  - https://github.com/portainer/portainer
#  - https://hub.docker.com/r/portainer/portainer

version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    networks:
      - default
    ports:
     - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
