#!/bin/bash

PROJECTDIR=`pwd`
DEFAULTDIR="/usr/local/bin"
DEFAULTARCH="arm-hf"

INSTALLDKRSCRIPTS=true
INSTALLDRY=true
INSTALLMDSTYLES=true
INSTALLPHP=true

printf "\n"

echo -n "Specify the absolute install path for project scripts (default is $DEFAULTDIR): "
read INSTALLDIR

echo -n "Specify CPU architecture ([arm-hf|x86-64] default is $DEFAULTARCH): "
read ARCH

# Configure

printf "\nConfiguration...\n\n"

if [ "$INSTALLDIR" = "" ]; then
  INSTALLDIR=$DEFAULTDIR
  echo "- Will use default install dir:" $INSTALLDIR
else
  echo "- Will install scripts into:" $INSTALLDIR
fi

if [ "$ARCH" = "" ]; then
  ARCH=$DEFAULTARCH
fi
echo "- Using CPU architecture:" $ARCH

# Install

printf "\nInstalling...\n\n"

# ... docker helper scripts

if [ "$INSTALLDKRSCRIPTS" = true ]; then
  for f in $( ls ./bin ); do
    echo "> Installing $PROJECTDIR/bin/$f into $INSTALLDIR/$f"
    ln -sf $PROJECTDIR/bin/$f $INSTALLDIR/$f
  done
fi

# ... moncho/dry

if [ "$INSTALLDRY" = true ]; then
  if [ "$ARCH" = "arm-hf" ] || [ "$ARCH" = "x86-64" ]; then
    echo "> Installing $PROJECTDIR/$ARCH/dry into $INSTALLDIR/dry"
    docker image rm dry:$ARCH
    pushd ./$ARCH/dry; ./build; popd
    ln -sf $PROJECTDIR/$ARCH/dry/dry $INSTALLDIR/dry
  fi
fi

# ... mixu/markdown-styles

if [ "$INSTALLMDSTYLES" = true ]; then
  if [ "$ARCH" = "x86-64" ]; then
    echo "> Installing $PROJECTDIR/$ARCH/generate-md into $INSTALLDIR/generate-md"
    docker image rm mdstyles:$ARCH
    pushd ./$ARCH/mdstyles; ./build; popd
    ln -sf $PROJECTDIR/$ARCH/mdstyles/generate-md $INSTALLDIR/generate-md
  fi
fi

# ... PHP / Composer

if [ "$INSTALLPHP" = true ]; then
  if [ "$ARCH" = "x86-64" ]; then
    echo "> Installing $PROJECTDIR/$ARCH/webdevops/php into $INSTALLDIR/php"
    ln -sf $PROJECTDIR/$ARCH/webdevops/php $INSTALLDIR/php

    echo "> Installing $PROJECTDIR/$ARCH/webdevops/php8 into $INSTALLDIR/php8"
    ln -sf $PROJECTDIR/$ARCH/webdevops/php $INSTALLDIR/php8

    echo "> Installing $PROJECTDIR/$ARCH/webdevops/php7 into $INSTALLDIR/php7"
    ln -sf $PROJECTDIR/$ARCH/webdevops/php $INSTALLDIR/php7

    echo "> Installing $PROJECTDIR/$ARCH/composer/composer into $INSTALLDIR/composer"
    ln -sf $PROJECTDIR/$ARCH/composer/composer $INSTALLDIR/composer
  fi
fi

printf "\nDone!\n\n"
