# ===== EmbyServer Service =====
#
# The EmbyServer Service
#
# ----- Notes -----
#
# Links:
#  - https://emby.media/
#
# Repos:
#  - https://hub.docker.com/r/emby/embyserver_arm32v7
#  - https://hub.docker.com/r/emby/embyserver/ (docs)

version: '3.8'

services:
  embyserver:
    container_name: embyserver
    image: emby/embyserver_arm32v7:latest
    environment:
      UID: 1000
      GID: 1000
      GIDLIST: 1000
    labels:
      # traefik v2 support
      - "traefik.http.routers.embyserver.rule=Host(`emby.dockerpi.homedev`)"
      - "traefik.http.routers.embyserver.entrypoints=web"
      - "traefik.http.services.embyserver.loadbalancer.server.port=8096"
      - "traefik.enable=true"
    devices:
      - "/dev/vchiq:/dev/vchiq"
    volumes:
      - /var/content/embyserver/config:/config
      - /var/content/media:/mnt/medialocal
    # Networking & DLNA
    #  - Enable network_mode: host to get DLNA working (disable networks, host mode precludes bridge networking)
    #  - Also re: DLNA, Traefik & Jellyfin, see: https://github.com/jellyfin/jellyfin/issues/1900#issuecomment-658073153
    # network_mode: host
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external:
      name: proxy
