# ===== SyncThing Service =====
#
# The SyncThing File Sync Service
#
# ----- Notes -----
#
# Links:
#  - https://syncthing.net
#
# Repos:
#  - https://hub.docker.com/r/syncthing/syncthing
#  - https://github.com/syncthing/syncthing

version: '3.8'

services:
  syncthing:
    image: syncthing/syncthing:1.22
    container_name: syncthing
    # Not stricly required, remove?
    #hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      # traefik v2 support
      - "traefik.http.routers.syncthing.entrypoints=web"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.dockerpi.homedev`)"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "traefik.tcp.routers.syncthing.entrypoints=st-file"
      - "traefik.tcp.routers.syncthing.rule=HostSNI(`*`)"
      - "traefik.tcp.services.syncthing.loadbalancer.server.port=22000"
      - "traefik.udp.routers.st-fileudp.entrypoints=st-fileudp"
      - "traefik.udp.routers.st-fileudp.service=syncthing"
      - "traefik.udp.services.syncthing.loadbalancer.server.port=22000"
      - "traefik.udp.routers.st-discovery.entrypoints=st-discovery"
      - "traefik.udp.routers.st-discovery.service=syncthing"
      - "traefik.udp.services.syncthing.loadbalancer.server.port=21027"
      - "traefik.enable=true"
    volumes:
      - /media/${USER}/ExternalContent960/services/syncthing:/var/syncthing
    # Networking:
    #  - Enable network_mode: host to improve auto discovery process & resulting sync speeds
    #  - See https://github.com/syncthing/syncthing/blob/main/README-Docker.md#discovery
    #network_mode: host
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external:
      name: proxy
