# ===== GOGS service =====
#
# The Go Git Service
#
# ----- Notes -----
#
# Links:
#  - https://gogs.io 
#
# Repos:
#  - https://hub.docker.com/r/gogs/gogs-rpi/
#  - https://github.com/gogits/gogs/tree/master/docker

version: '3.2'

services:
  gogs:
    container_name: gogs
    image: gogs/gogs-rpi:0.12
    labels:
      # traefik v2 support
      - "traefik.http.routers.gogs.rule=Host(`gogs.dockerpi.homedev`)"
      - "traefik.http.services.gogs.loadbalancer.server.port=3000"
      - "traefik.enable=true"
    volumes:
      - /var/gogs:/data
    ports:
      - "2022:22"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external:
      name: proxy
