#!/bin/bash

# Constants
NGINXIMAGE="nginx"
PHPFPMIMAGE="php-fpm"
DEFAULTTAG="alpine"
NGINXCONTAINER="nginxtest"
PHPFPMCONTAINER="phpfpmtest"
DEFAULTHOST="nginxphptest.dockerpi.homedev"

# Reset optargs (assume previously used)
OPTIND=1

# Variants
ACTION=""
TAG=""
HOST=""
DESTCONFIG=""

# Parse arguments
while getopts "h?s?t:?" opt; do
  case "$opt" in
    h)
      printf "\nrun : Begin a test run of the image\n\n"
      printf "Usage: run [-t tagname] [-s]\n\n"
      printf "  -t tagname : Tag name to use for the test image\n"
      printf "  -s         : Stop a previously started test run\n\n"
      exit 0;
      ;;
    t) TAG=$OPTARG 
      ;;
    s) ACTION="stop"
      ;;
  esac
done

if [ "$TAG" = "" ]; then
  TAG=$DEFAULTTAG
fi

if [ "$TAG" = "alpine" ]; then
  DESTCONFIG="/etc/nginx/conf.d/default.conf"
else
  DESTCONFIG="/etc/nginx/sites-available/default"
fi

if [ "$ACTION" = "" ]; then

  # Start test run 

  printf "\nTesting nginx + php-fpm images (using containers $NGINXCONTAINER + $PHPFPMCONTAINER and images $NGINXIMAGE:$TAG + $PHPFPMIMAGE:$TAG)\n"
  printf "\nEnter a hostname (blank for default): "
  read HOST

  if [ "$HOST" = "" ]; then
    HOST=$DEFAULTHOST
  fi

  printf "\nThe default Nginx + PhpFPM page should be available at\n"
  printf " - 'http://$HOST' if using the jwilder Nginx proxy\n"
  printf " - 'http://localhost' otherwise\n\n"

  docker run -d --rm --name $PHPFPMCONTAINER --network=proxy \
    -v $PWD/test/index.php:/var/www/html/index.php \
    $PHPFPMIMAGE:$TAG

  docker run -d --rm -e VIRTUAL_HOST=$HOST --name $NGINXCONTAINER \
    --network=proxy --link $PHPFPMCONTAINER \
    -v $PWD/test/index.php:/var/www/html/index.php \
    -v $PWD/test/default.conf:$DESTCONFIG \
    $NGINXIMAGE:$TAG

elif [ "$ACTION" = "stop" ]; then

  # Stop test run

  echo "Stopping test container '$NGINXCONTAINER'"
  docker stop $NGINXCONTAINER

  echo "Stopping test container '$PHPFPMCONTAINER'"
  docker stop $PHPFPMCONTAINER

  echo "All done!"

fi
