# ===== Nginx reverse proxy =====
#
# Nginx reverse proxy (jwilder implementation)
#
# ----- Notes -----
#
# Articles:
#  - http://jasonwilder.com/blog/2014/03/25/automated-nginx-reverse-proxy-for-docker/
#
# Repos:
#  - https://github.com/jwilder/nginx-proxy

version: '3'

services:
  nginx-proxy:
    container_name: proxy
    image: jwilder/nginx-proxy:latest
    networks:
      - proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

networks:
  proxy:
    external:
      name: proxy
