#!/bin/bash

# Traefik first run setup -----

if [ $( docker network ls --format="{{.Name}}" | grep -E "^proxy$" ) ]; then
  echo "Traefik proxy network already setup, skipping..."
else
  echo "Setting up Traefik proxy network..."
  docker network create proxy
fi
