providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.dockerpi.homedev`)"
    endpoint: "http://dockerproxy:2375"
    exposedByDefault: false

api:
  dashboard: true
  insecure: true

log:
  level: ERROR

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  dns:
    address: ":53/tcp"
  dnsudp:
    address: ":53/udp"
  ssh:
    address: ":22/tcp"
  st-file:
    address: ":20000/tcp"
  st-fileudp:
    address: ":20000/udp"
  st-discovery:
    address: ":21027/udp"

#http:
#  routers:
#    api:
#      rule: Host(`traefik.dockerpi.homedev`)
#      service: api@internal
