debug = false
loglevel = "ERROR"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "dockerpi.homedev"
watch = true
exposedbydefault = false

[api]
dashboard = true

[ping]

