# ===== NextCloud Service =====
#
# The NextCloud Service
#
# ----- Notes -----
#
# Links:
#  - https://nextcloud.com/
#
# Repos:
#  - https://hub.docker.com/_/nextcloud
#  - https://github.com/nextcloud/docker

version: '3.8'

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:21-apache
    labels:
      # traefik v2 support
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.dockerpi.homedev`)"
      - "traefik.http.routers.nextcloud.entrypoints=web"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.enable=true"
    volumes:
      - /var/content/nextcloud/main:/var/www/html
      - /var/content/nextcloud/config:/var/www/html/config
      - /var/content/nextcloud/apps:/var/www/html/custom_apps
      - /var/content/nextcloud/data:/var/www/html/data
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external:
      name: proxy
