#!/bin/bash

ACTION=$1
IMAGE="nginx"
CONTAINER="nginxtest"
DEFAULTHOST="nginxtest.dockerpi.homedev"
HOST=""

if [ "$ACTION" = "" ]; then

  printf "\nTesting nginx image (using container name $CONTAINER)\n"
  printf "\nEnter a hostname (blank for default): "
  read HOST

  if [ "$HOST" = "" ]; then
    HOST=$DEFAULTHOST
  fi

  printf "\nThe default Nginx page should be available at\n"
  printf " - 'http://$HOST' if using the jwilder Nginx proxy\n"
  printf " - 'http://localhost' otherwise\n\n"

  docker run -d -e VIRTUAL_HOST=$HOST --name $CONTAINER --network=proxy $IMAGE

elif [ "$ACTION" = "--stop" ] || [ "$ACTION" = "-s" ]; then

  echo "Stopping test container '$CONTAINER'"
  docker stop $CONTAINER

  echo "Removing test container '$CONTAINER'"
  docker rm $CONTAINER

  echo "All done!"

fi
