#!/bin/bash

ACTION=$1
IMAGE="nginx-php70"
CONTAINER="nginxphptest"
DEFAULTHOST="$CONTAINER.dockerpi.homedev"
HOST=""

if [ "$ACTION" = "" ]; then

  printf "\nTesting nginx image (using container name $CONTAINER)\n"
  printf "\nEnter a hostname (blank for default): "
  read HOST

  if [ "$HOST" = "" ]; then
    HOST=$DEFAULTHOST
  fi

  printf "\nThe test Nginx+PHP page should be available at\n"
  printf " - 'http://$HOST' if using the jwilder Nginx proxy\n"
  printf " - 'http://localhost' otherwise\n\n"

  docker run -d --rm -e VIRTUAL_HOST=$HOST --name $CONTAINER --network=proxy \
    -v $PWD/config/default:/etc/nginx/sites-available/default \
    -v $PWD/data:/var/www/html \
    $IMAGE

elif [ "$ACTION" = "--stop" ] || [ "$ACTION" = "-s" ]; then

  echo "Stopping test container '$CONTAINER'"
  docker stop $CONTAINER

  echo "All done!"

fi
