FROM arm32v6/alpine:latest 

RUN set -x && \
    apk update && \
    apk upgrade && \
    apk add bash salt-master

RUN rm -rf /var/cache/apk/*

RUN mkdir -p /srv/salt && \ 
    mkdir -p /srv/pillar

COPY config/master /etc/salt/master

ADD state/ /srv/

EXPOSE 4505 4506

CMD ["salt-master"]
