FROM arm32v6/alpine:latest 

RUN set -x && \
    apk update && \
    apk upgrade && \
    apk add bash salt-master

RUN rm -rf /var/cache/apk/*

RUN mkdir -p /srv/salt 

COPY master /etc/salt/master

ADD states/ /srv/salt/

EXPOSE 4505 4506

CMD ["salt-master"]
