# ===== Nginx reverse proxy service =====
#
# ----- Notes -----
#
# Articles:
#  - https://fourteenislands.io/2016/04/nginx-reverse-proxy-docker-and-a-raspberry-pi/
#
# Repos:
#  - https://github.com/lroguet/rpi-nginx-proxy
#  - https://github.com/jwilder/nginx-proxy

version: '3.2'

services:
  nginx-proxy:
    container_name: proxy
    image: lroguet/rpi-nginx-proxy:latest
    environment:
      - DEFAULT_HOST=pihole.dockerpi.homedev
    networks:
      - proxy
    ports:
     - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $PWD/default:/etc/nginx/sites-available/default
    restart: unless-stopped

networks:
  proxy:
    external:
      name: proxy
