# ===== Core routing services =====
#
# Nginx reverse proxy (jwilder based implementation)
# Pihole DNS filter
#
# ----- Notes -----
#
# Article: https://fourteenislands.io/2016/04/nginx-reverse-proxy-docker-and-a-raspberry-pi/
#
# Proxy (jwilder derived):
#  - https://hub.docker.com/r/lroguet/rpi-nginx-proxy/
#  - https://github.com/jwilder/nginx-proxy
#
# Pi-hole: 
#  - https://hub.docker.com/r/diginc/pi-hole/
#  - https://github.com/diginc/docker-pi-hole

version: '3'

services:
  nginx-proxy:
    container_name: proxy
    image: lroguet/rpi-nginx-proxy:latest
    environment:
      - DEFAULT_HOST=pihole.dockerpi.homedev
    networks:
      - proxy
    ports:
     - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $PWD/default:/etc/nginx/sites-available/default
    restart: unless-stopped

  pihole:
    image: diginc/pi-hole:arm
    env_file: .env
    environment:
      - VIRTUAL_HOST=pihole.dockerpi.homedev
    volumes:
      - $PWD/configs/pihole/:/etc/pihole/
      - $PWD/configs/dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80/tcp"
    networks:
      - proxy
      - default
    depends_on:
      - nginx-proxy
    restart: unless-stopped

networks:
  proxy:
    external:
      name: proxy
