#!/bin/bash

TTY=
ENTRYPOINT=
CMD="php"
ARGS="$@"

if [ $1 = "shell" ]; then
  TTY="--tty"
  ENTRYPOINT="--entrypoint /bin/bash"
  CMD=""
  ARGS=""
fi

docker run \
  --rm \
  --interactive \
  --network=host \
  ${TTY} \
  -v "${HOME}":"${HOME}":ro \
  -u $(id -u) \
  -w "${PWD}" \
  ${ENTRYPOINT} \
  webdevops/php:latest \
  $CMD $ARGS
