#!/bin/bash

ENTRYPOINT=
CMD="php"
ARGS="$@"

if [ $1 = "shell" ]; then
  ENTRYPOINT="--entrypoint /bin/bash"
  ARGS=""
  CMD=""
fi

docker run \
  --rm \
  --interactive \
  --tty \
  --network=host \
  -v "${HOME}":"${HOME}":ro \
  -u $(id -u) \
  -w "${PWD}" \
  ${ENTRYPOINT} \
  webdevops/php:latest \
  $CMD $ARGS
