#!/bin/bash

IP_LOOKUP="$(ip route get 8.8.8.8 | awk '{ print $NF; exit }')"
#IPv6_LOOKUP="$(ip -6 route get 2001:4860:4860::8888 | awk '{ print $10; exit }')"
IP="${IP:-$IP_LOOKUP}"
#IPv6="${IPv6:-$IPv6_LOOKUP}"

rm -f .env
touch .env

echo "IP_LOOKUP=$IP_LOOKUP" >> .env
echo "IP=$IP" >> .env

echo "Created .env file as follows:"
cat .env
