# Nginx docs instance

version: '3'

services:
  dns:
    image: diginc/pi-hole:arm
    env_file: .env
    environment:
      - VIRTUAL_HOST=pihole.dockerpi.homedev
    volumes:
      - $PWD/configs/pihole/:/etc/pihole/
      - $PWD/configs/dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80/tcp"
    networks:
      - proxy
      - default
    restart: unless-stopped

networks:
  proxy:
    external:
      name: proxy
