# ===== Pihole DNS filter service =====
#
# Note the /etc/resolv.conf mount is temporary until Pihole updated to v3.2.1 r1856 or greater
#
# ----- Notes -----
#
# Repos:
#  - https://hub.docker.com/r/pihole/pihole/
#  - https://github.com/pi-hole/docker-pi-hole

version: '3.2'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:v5.1.2
    env_file: .env
    labels:
      # traefik v2 support
      - "traefik.http.routers.pihole.rule=Host(`pihole.dockerpi.homedev`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.enable=true"
    volumes:
    # - $PWD/configs/resolv.conf:/etc/resolv.conf
      - $PWD/configs/pihole/:/etc/pihole/
      - $PWD/configs/dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external:
      name: proxy
