FROM arm32v6/alpine:latest 

RUN set -x && \
    apk update && \
    apk upgrade && \
    apk add bash salt-minion
    
RUN rm -rf /var/cache/apk/*

COPY config/minion /etc/salt/minion

CMD ["salt-minion"]
