version: '3'

services:
  salt-master:
    container_name: salt
    image: saltmaster:arm
    networks:
      - default
    ports:
     - "4505:4505"
     - "4506:4506"

  salt-minion:
    image: saltminion:arm
    networks:
      - default
    depends_on:
      - salt-master
