# ===== Documentation web server =====
#
# Using Nginx web server based on the official Nginx Alpine image
#
# ----- Notes -----
#
# Repos:
#  - https://hub.docker.com/_/nginx/

version: '3.2'

services:
  web:
    image: nginx:alpine
    environment:
      # lroguet/rpi-nginx-proxy support
      - VIRTUAL_HOST=docs.dockerpi.homedev
    labels:
      # traefik support
      - "traefik.backend=docs" 
      - "traefik.frontend.rule=Host:docs.dockerpi.homedev"
    volumes:
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/pi/content/docs/src:/usr/share/nginx/html
    networks:
      - proxy
    #  - default
    restart: unless-stopped

networks:
  proxy:
    external:
      name: proxy
