# ===== Documentation web server =====
#
# Using Nginx web server based on the lroguet/rpi-nginx image
#
# ----- Notes -----
#
# Repos:
#  - https://github.com/lroguet/rpi-nginx

version: '3'

services:
  web:
    image: lroguet/rpi-nginx:latest
    environment:
      - VIRTUAL_HOST=docs.dockerpi.homedev
    volumes:
      - $PWD/nginx.conf:/etc/nginx/sites-enabled/default
      - /home/pi/content/docs/src:/var/www/html
    networks:
      - proxy
      - default
    restart: unless-stopped

networks:
  proxy:
    external:
      name: proxy
