# ===== Documentation web server =====
#
# Using Nginx web server based on the official Nginx Alpine image
#
# ----- Notes -----
#
# Repos:
#  - https://hub.docker.com/_/nginx/

version: '3.2'

services:
  web:
    container_name: docs
    image: nginx:alpine
    labels:
      # traefik v2 support
      - "traefik.http.routers.docs.rule=Host(`docs.dockerpi.homedev`)"
      - "traefik.http.routers.docs.entrypoints=web"
      - "traefik.http.services.docs.loadbalancer.server.port=80"
      - "traefik.enable=true"
    volumes:
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
      - /media/${USER}/ExternalContent960/services/docs/web:/usr/share/nginx/html
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external:
      name: proxy
