# ===== Nginx (test) web server =====
#
# Nginx web server test instance based on the lroguet/rpi-nginx image
#
# ----- Notes -----
#
# Articles:
#  - https://fourteenislands.io/2016/04/nginx-reverse-proxy-docker-and-a-raspberry-pi/
#
# Repos:
#  - https://github.com/lroguet/rpi-nginx

version: '3'

services:
  web:
    #container_name: nginx-test
    image: lroguet/rpi-nginx:latest
    environment:
    - VIRTUAL_HOST=test.dockerpi.homedev
    volumes:
      - $PWD/html:/var/www/html
    networks:
      - proxy
      - default

networks:
  proxy:
    external:
      name: proxy
